project:
  type: website
  render:
    - index.qmd
    - content/AFSC-GOA-pollock.qmd
    - content/NEFSC-yellowtail.qmd
    - content/pacific-hake.qmd
    - content/PIFSC-opakapaka.qmd

website:
  page-navigation: true
  title: "NOAA FIMS case studies"
  site-url: "https://noaa-fims.github.io/case-studies"
  repo-url: "https://github.com/NOAA-FIMS/case-studies"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/NOAA-FIMS/case-studies
        text: "NOAA FIMS case studies"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/NEFSC-yellowtail.qmd
        text: S New England-Mid Atlantic yellowtail flounder
      - href: content/AFSC-GOA-pollock.qmd
        text: Gulf of Alaska pollock
      # - href: content/SWFSC-sardine.qmd
      #   text: sardine
      # - href: content/PIFSC-opakapaka.qmd
      #   text: Opakapaka
      # - href: content/NWFSC-petrale.qmd
      #   text: petrale sole
      # - href: content/SEFSC-scamp.qmd
      #   text: scamp
      - href: content/pacific-hake.qmd
        text: Pacific Hake
      # - href: content/advanced-features.qmd
      #   text: Advanced features
      - href: content/acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto


