---
title: NWFSC Case Study Petrale Sole
format:
  html:
    code-fold: true
---

## The setup

{{< include setup.qmd >}}

```{r}
#| label: setup-objects
common_name <- "Petrale sole"

# convert SS3 data into FIMS format and convert to FIMSFrame object
data_4_model <- r4ss::ss3_data_to_fims(
    ss3_dir = "https://raw.githubusercontent.com/pfmc-assessments/petrale/main/models/2023.a050.003_FIMS_case-study_wtatage/",
    ss_new = TRUE
) |>
    FIMS::FIMSFrame()

# read SS3 output files from petrale sole assessment on GitHub
rep <- r4ss::SS_output(
    "https://raw.githubusercontent.com/pfmc-assessments/petrale/main/models/2023.a050.003_FIMS_case-study_wtatage",
    printstats = FALSE,
    verbose = FALSE,
    covar = FALSE
)
# alternative output processing using stockplotr
output_petrale <- stockplotr::convert_output(
    "https://raw.githubusercontent.com/pfmc-assessments/petrale/main/models/2023.a050.003_FIMS_case-study_wtatage/Report.sso",
    model = "ss3"
)

```

## Run FIMS model

```{r, max.height='100px', attr.output='.numberLines'}
#| label: setup-model

# lots of code below copied PIFSC-opakapaka.qmd
years <- (data_4_model |> FIMS::get_start_year()):(data_4_model |>
    FIMS::get_end_year())
ages <- data_4_model |> FIMS::get_ages()

# Create default parameters
default_parameters <- FIMS::create_default_configurations(
    data = data_4_model
) |>
    FIMS::create_default_parameters(
        data = data_4_model
    ) |>
    tidyr::unnest(cols = data)

recdevs <- rep$recruitpars |> # $recruitpars is a subset of $parameters with Yr as an additional column
    dplyr::filter(Yr %in% years) |> # filter out initial numbers parameters
    dplyr::select(Yr, Value)

init_naa <- rep$natage |>
    dplyr::filter(Time == min(years), Sex == 1) |> # numbers at age in FIMS start year, not SS3 model
    dplyr::select(paste(ages)) |>
    as.numeric() # TODO: figure out if *1000 is needed
init_naa <- exp(
    rep$parameters |> dplyr::filter(grepl("R0", Label)) |> dplyr::pull(Init)
) *
    1000 *
    exp(
        -(ages - 1) *
            rep$parameters |>
                dplyr::filter(grepl("NatM.*Fem", Label)) |>
                dplyr::pull(Value)
    )
init_naa[length(ages)] <- init_naa[length(ages)] /
    rep$parameters |>
        dplyr::filter(grepl("NatM.*Fem", Label)) |>
        dplyr::pull(Value) # sum of infinite series

parameters <- default_parameters |>
    # SS3 model had length-based selectivity which leads to sex-specific
    # age-based selectivity due to sexually-dimorphic growth.
    # I didn't bother to calculate an age-based inflection point averaged over sexes
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Maturity",
            label = c("inflection_point", "slope"),
            value = c(20.5, 1.8), # arbitrary guess of slope
        ),
        by = c("module_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Selectivity",
            fleet_name = "fleet1",
            label = c("inflection_point", "slope"),
            value = c(10, 2),
            estimation_type = "constant"
        ),
        by = c("module_name", "fleet_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Selectivity",
            fleet_name = "fleet2",
            label = c("inflection_point", "slope"),
            value = c(10, 2),
            estimation_type = "constant"
        ),
        by = c("module_name", "fleet_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Selectivity",
            fleet_name = "fleet4",
            label = c("inflection_point", "slope"),
            value = c(6, 2),
            estimation_type = "constant"
        ),
        by = c("module_name", "fleet_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Recruitment",
            label = c("log_rzero", "logit_steep", "log_sd"),
            value = c(
                rep$parameters |>
                    filter(grepl(pattern = "SR_LN(R0)", Label, fixed = TRUE)) |>
                    pull(Value),
                FIMS::logit(
                    0.2,
                    1.0,
                    rep$parameters |>
                        filter(grepl(
                            pattern = "SR_BH_steep",
                            Label,
                            fixed = TRUE
                        )) |>
                        pull(Value)
                ),
                0.5
            )
        ),
        by = c("module_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Recruitment",
            label = "log_devs",
            time = (FIMS::get_start_year(data_4_model) + 1):(FIMS::get_end_year(
                data_4_model
            )),
            # The last value of the initial numbers at age is the first
            # recruitment deviation
            value = recdevs$Value[-1],
        ),
        by = c("module_name", "label", "time")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Population",
            label = "log_init_naa",
            age = FIMS::get_ages(data_4_model),
            value = log(init_naa),
            estimation_type = "fixed_effects"
        ),
        by = c("module_name", "label", "age")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Population",
            label = "log_M",
            value = log(rep$parameters["NatM_uniform_Fem_GP_1", "Value"]),
            estimation_type = "constant"
        ),
        by = c("module_name", "label")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Fleet",
            fleet_name = "fleet1",
            time = years,
            label = "log_Fmort",
            estimation_type = "constant",
            value = rep[["exploitation"]] |>
                dplyr::filter(Yr %in% years) |>
                dplyr::mutate(North = ifelse(North == 0, -999, log(North))) |>
                dplyr::pull(North)
        ),
        by = c("module_name", "fleet_name", "label", "time")
    ) |>
    dplyr::rows_update(
        tibble::tibble(
            module_name = "Fleet",
            fleet_name = "fleet2",
            time = years,
            label = "log_Fmort",
            estimation_type = "constant",
            value = rep[["exploitation"]] |>
                dplyr::filter(Yr %in% years) |>
                dplyr::mutate(South = ifelse(South == 0, -999, log(South))) |>
                dplyr::pull(South)
        ),
        by = c("module_name", "fleet_name", "label", "time")
    )

# Run the model without optimization to help ensure a viable model
test_fit <- parameters |>
    FIMS::initialize_fims(data = data_4_model) |>
    FIMS::fit_fims(optimize = FALSE)

# Run the  model with optimization
fit <- parameters |>
    FIMS::initialize_fims(data = data_4_model) |>
    FIMS::fit_fims(optimize = TRUE, get_sd = FALSE)
```

## Plotting results

```{r}
#| label: comparison-plots
# gather index fit info
index_results <- data.frame(
    observed = FIMS::m_index(data_4_model, "fleet4"),
    expected = FIMS::get_report(fit)[["index_expected"]][[2]]
) |>
    dplyr::mutate(year = years) |>
    dplyr::filter(observed > 0) # filter out -999 rows

# plot index fit
ggplot2::ggplot(index_results, ggplot2::aes(x = year, y = observed)) +
    ggplot2::geom_point() +
    ggplot2::xlab("Year") +
    ggplot2::ylab("Index (mt)") +
    ggplot2::geom_line(ggplot2::aes(x = year, y = expected), color = "blue") +
    ggplot2::theme_bw()


# gather catch info
catch_results <- data.frame(
    year = years,
    observed = FIMS::m_landings(data_4_model, fleet = "fleet1"),
    expected = FIMS::get_report(fit)[["landings_expected"]][[1]]
)

# plot catch fit
ggplot2::ggplot(catch_results, ggplot2::aes(x = year, y = observed)) +
    ggplot2::geom_point() +
    #ggplot2::aes(color = fleet)) +
    ggplot2::xlab("Year") +
    ggplot2::ylab("Catch (mt)") +
    ggplot2::geom_line(ggplot2::aes(x = year, y = expected)) + #, color = fleet)) +
    ggplot2::theme_bw()

# gather biomass info from FIMS and SS3
biomass <- rep$timeseries |>
    dplyr::select(Yr, SpawnBio, Bio_all) |>
    dplyr::filter(Yr %in% years) |>
    dplyr::rename(
        "SS3_SpawnBio" = "SpawnBio",
        "SS3_Bio" = "Bio_all"
    ) |>
    dplyr::mutate(
        FIMS_SpawnBio = FIMS::get_report(fit)[["spawning_biomass"]][[1]][-1],
        FIMS_Bio = FIMS::get_report(fit)[["biomass"]][[1]][-1]
    ) |> ##CHECK: Is FIMS ssb reporting n_years+1 or initial year-1?
    tidyr::pivot_longer(cols = -Yr) |>
    tidyr::separate_wider_delim(
        cols = "name",
        delim = "_",
        names = c("Model", "Type")
    )

# plot comparison of spawning biomass and total biomass time series
ggplot2::ggplot(biomass, ggplot2::aes(x = Yr, y = value)) +
    ggplot2::geom_line(ggplot2::aes(color = Model)) +
    ggplot2::xlab("Year") +
    ggplot2::ylab("") +
    ggplot2::facet_wrap(~Type, scales = "free_y") +
    ggplot2::theme_bw()

# gather info on recruitment
recruits <- rep$recruit |>
    dplyr::filter(Yr %in% years) |>
    dplyr::select(Yr, exp_recr, raw_dev) |>
    dplyr::rename(
        "SS3_recruit" = "exp_recr",
        "SS3_recdev" = "raw_dev",
        "Year" = "Yr"
    ) |>
    dplyr::mutate(
        FIMS_recruit = c(FIMS::get_report(fit)[["expected_recruitment"]][[1]][
            -1
        ]),
        FIMS_recdev = c(
            NA,
            FIMS::get_estimates(fit) |>
                dplyr::filter(
                    module_name == "Recruitment",
                    label == "log_devs"
                ) |>
                dplyr::pull(estimated)
        ),
        SS3_recruit = SS3_recruit * 1000
    ) |>
    tidyr::pivot_longer(cols = -Year) |>
    tidyr::separate_wider_delim(
        cols = "name",
        delim = "_",
        names = c("Model", "Type")
    )

# plot recruit time series
ggplot2::ggplot(recruits, ggplot2::aes(x = Year, y = value, color = Model)) +
    ggplot2::geom_line() +
    ggplot2::facet_wrap(~Type, scales = "free_y") +
    ggplot2::theme_bw()

```

```{r}
#| label: cleanup
#| output: false
#| warning: false
FIMS::clear()
```
