```{r}
#| warning: false
#| label: package-installation
#| eval: false
#| echo: false

# Names of required packages
packages <- c(
  "dplyr",
  "ggplot2",
  "gt",
  "here",
  "lubridate",
  "remotes",
  "reshape2",
  "shinystan",
  "tidyr",
  "TMB"
)

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], repos = "http://cran.us.r-project.org")
}

# the Bayesian case study requires these extra packages
if (!"StanEstimators" %in% rownames(installed.packages())) {
  install.packages("StanEstimators", repos = c("https://andrjohns.r-universe.dev", "https://cloud.r-project.org"))
}

if (!"adnuts" %in% rownames(installed.packages())) {
  remotes::install_github("Cole-Monnahan-NOAA/adnuts", ref="sparse_M")
}

# SS3 case studies require r4ss
if (!"r4ss" %in% rownames(installed.packages())) {
  remotes::install_github("r4ss/r4ss")
}

# Install FIMS: main branch version if on main, dev version on any other branch

branch_name <- system("git branch --show-current", intern = TRUE)
#use_fims_main <- grepl("main", branch_name)

if (branch_name == "main") {
  # Use default profile
  Sys.unsetenv("RENV_PROFILE")
  message("Using default renv profile for main branch")
} else {
  # Use dev profile
  Sys.setenv(RENV_PROFILE = "dev")
  message("Using dev renv profile for branch: ", current_branch)
}

# Load packages
invisible(lapply(packages, library, character.only = TRUE))

library(FIMS)
library(adnuts)
R_version <- version$version.string
TMB_version <- packageDescription("TMB")$Version
FIMS_commit <- substr(packageDescription("FIMS")$GithubSHA1, 1, 7)

source(file.path("R", "utils.R"))
```


```{r}
branch_name <- system("git branch --show-current", intern = TRUE)
#use_fims_main <- grepl("main", branch_name)

if (branch_name == "main") {
  # Use default profile
  Sys.unsetenv("RENV_PROFILE")
  message("Using default renv profile for main branch")
} else {
  # Use dev profile
  Sys.setenv(RENV_PROFILE = "dev")
  message("Using dev renv profile for branch: ", current_branch)
}

library(FIMS)
library(adnuts)
R_version <- version$version.string
TMB_version <- packageDescription("TMB")$Version
FIMS_commit <- substr(packageDescription("FIMS")$GithubSHA1, 1, 7)

source(file.path("R", "utils.R"))
```

