---
title: Customize
---

## Edit and add your pages

Each page should start with 
```
---
title: your title
---
```
and the first header will be the 2nd level, so `## `. Note, there are situations where you leave off
```
---
title: your title
---
```
and start the qmd file with a level header `# `, but if using the default title yaml (in the `---` fence) is a good habit since it makes it easy for Quarto convert your qmd file to other formats (like into a presentation).

## Add a chunk of code describing your setup

Case study files should include:
* R version
* TMB version
* FIMS commit
* Name of your stock
* Name of your region
* Name of the analyst

## Add a bulleted list and script describing simplifications you had to make

How I simplified my assessment
* Remove seasonality
* Sum the catch values for MexCal S1 and S2
* Sum the age comps for MexCal S1 and S2
* Drop spring AT survey index values
* Assume Q=1 for AT survey, rather than have annual values
* Assume time-invariant logistic selectivity PNW and AT survey fleets
* Assume time-invariant double logistic selectivity MexCal fleet
* Lorenzen age M -> one M value
 

## Add your script that sets up and runs the model
```{r}
load("data_files/sardine2024.Rdata")

#------key to convert model years to calendar years
times <- sardine2024$timeseries %>% select(Yr, Seas)
times$calyear <- times$Yr
times[which(times$Seas == 2), 'calyear'] <- times[which(times$Seas == 2), 'calyear'] + 1
times$datestart <- paste0(times$calyear, "-01-01")
times$dateend <- paste0(times$calyear, "-06-30")

#Change for seas 1
times[which(times$Seas == 1), 'datestart'] <- paste0(times[which(times$Seas == 1), 'calyear'],
                                                     "-07-01")
times[which(times$Seas == 1), 'dateend'] <- paste0(times[which(times$Seas == 1), 'calyear'],
                                                     "-12-31")

#------catch data
#FIMS formatting
#type, name, age, datestart, dateend, value, unit, uncertainty

#Catch 
landings <- sardine2024$catch %>% select(Fleet, Yr, Seas, Obs, se) %>%
  filter(Yr > 2004)
landings$type <- "landings"
landings$name <- paste0("fleet", landings$Fleet)
landings <- landings %>% left_join(times, by = c("Yr", "Seas"))
landings$unit <- "mt"
landings$uncertainty <- landings$se

#Create key for changing model year to calendar year
expand(Yr = 20)

times  <- tibble(Yr = 2005:2023)
times <- times %>% expand(Yr, Seas = 1:2)


landings$cal_year


landings %>% distinct(Seas) %>% mutate(start = c("-07-01", "01-01"))


landings$datestart <- paste0(landings$Yr, "-07-01")
landings$dateend <- paste0(landings$Yr, "-12-31")

landings[which(landings$Seas == 2), 'datestart']


#Might have to keep the model summer only
unit = "mt"
uncertainty <- 0.05

#CPUE
sardine2024$cpue

#Age comp


#Weight-at-age




```


## Add your comparison figures

## Add comparison tables

## What was your experience using FIMS? What could we do to improve usability?

## List any issues that you ran into or found

Please [open an issue](https://github.com/NOAA-FIMS/FIMS/issues/new/choose) if you found something new.

## What features are most important to add based on this case study?

## Add your pages to the project

* Add the files to `_quarto.yml`

