on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
      - 74-feature-set-up-renv
  workflow_dispatch:
  schedule: 
    - cron: '30 0 * * 0' # runs At 00:00 on Sunday

name: Render

jobs:
  build-deploy:
    runs-on: macos-latest
    env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

     # - name: Install packages (needed for Rmd)
     #   run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "jsonlite"))'
      - name: Install R packages with renv
        uses: r-lib/actions/setup-renv@v2
        with: 
          profile: "dev"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      - name: Render Quarto Project 
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
