on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
      - 74-feature-set-up-renv
  workflow_dispatch:
  schedule: 
    - cron: '30 0 * * 0' # runs At 00:00 on Sunday

name: Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0  # Get full history and all branch contents

      - name: Check branch and commit
        run: |
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit: $(git rev-parse HEAD)"
          echo "Log:"
          git log --oneline -n 5  
          
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for R packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev libxml2-dev libcurl4-openssl-dev libjpeg-dev libfontconfig1-dev pandoc
      
      - name: Determine renv profile
        id: profile
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]] || [[ "${{ github.base_ref }}" == "dev" ]]; then
            echo "profile=dev" >> $GITHUB_OUTPUT
          else
            echo "profile=default" >> $GITHUB_OUTPUT
          fi

      - name: Print the output
        run: |
          echo "The profile is: ${{ steps.profile.outputs.profile }}"

      - name: Activate and inspect renv profile
        run: |
          Rscript -e "install.packages('renv', repos = 'https://cloud.r-project.org')"
          # Set lockfile based on the profile output from previous step
          profile="${{ steps.profile.outputs.profile }}"
          echo "Detected profile: $profile"

          if [[ "$profile" == "dev" ]]; then
            lockfile="renv/profiles/dev/renv.lock"
          else
            lockfile="renv/renv.lock"
          fi

          echo "Using lockfile: $lockfile"
          Rscript -e "source('./content/renv-profile.R')"
          Rscript -e "
            lockfile <- '${lockfile}'
            message('Using lockfile: ', lockfile)
            if (file.exists(lockfile)) {
              lock <- renv::lockfile_read(lockfile)
              cat('Read lockfile with', length(lock$Packages), 'packages\n')
              if ('FIMS' %in% names(lock$Packages)) {
                pkg <- lock$Packages[['FIMS']]
                cat('FIMS version:', pkg$$RemoteRef, '\n')
              }
            } else{
            cat('Lockfile not found: ', lockfile, '\n')}
          "
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
  
      - name: Check if lockfile was modified
        run: |
          echo "Git diff of lockfile:"
          git diff renv/profiles/dev/renv.lock || echo "No diff or file missing"

      # - name: Install R packages with renv
      #   uses: r-lib/actions/setup-renv@v2
      #   env:
      #     RENV_PROFILE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && '' || 'dev' }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      # - name: Render Quarto Project 
      #   uses: quarto-dev/quarto-actions/render@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
